/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./assets/js/*.js"],
  theme: {
    extend: {
      colors: {
        "surface": "#f9f9fe",
        "surface-dim": "#d9dade",
        "surface-bright": "#f9f9fe",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f8",
        "surface-container": "#ededf2",
        "surface-container-high": "#e8e8ed",
        "surface-container-highest": "#e2e2e7",
        "surface-variant": "#e2e2e7",
        "on-surface": "#1a1c1f",
        "on-surface-variant": "#4f4350",
        "outline": "#807381",
        "outline-variant": "#d2c1d2",
        "background": "#f9f9fe",
        "on-background": "#1a1c1f",
        "primary": "#8935a7",
        "on-primary": "#ffffff",
        "primary-container": "#a550c2",
        "on-primary-container": "#fffbff",
        "secondary": "#0058bc",
        "on-secondary": "#ffffff",
        "secondary-container": "#0070eb",
        "on-secondary-container": "#fefcff",
        "tertiary": "#8d4559",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#aa5d72",
        "on-tertiary-container": "#fffbff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "deep-navy": "#1C1C1E",
        "electric-blue": "#0A84FF",
        "electric-cyan": "#5AC8FA",
        "vibrant-pink": "#DC8CDB",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        unit: "8px",
        "margin-mobile": "24px",
        gutter: "24px",
        "margin-desktop": "80px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
